### ISSUE TITLE
mnh exits unexpectly if UPnP is not supported on router

### ISSUE THREAD

**Issue by Provissy** [hzyitc/mnh#2]
```
2021/05/25 19:30:59 main.go:79: NewDemoWeb error: no UPnP-enabled gateway found
```

**Comment by hzyitc** [comment]
I thought if you need UPnP, it mean your router will block the incoming traffic. So if UPnP fail, mnh can't work. If your router not block incoming traffic, just disable UPnP.

**Comment by Provissy** [comment]
> I thought if you need UPnP, it mean your router will block the incoming traffic. So if UPnP fail, mnh can't work. If your router not block incoming traffic, just disable UPnP.

The router may not have UPnP function and accepts all traffics, for example, a FTTH ONU. 

I think making UPnP function disabled by default is a better option.

**Comment by hzyitc** [comment]
But i thought most of router will block new incoming traffic instand of allowing. 
And also, making UPnP enabled by default is friendly for new users. Because when he/she see this error, he/she will try to disable it or enable UPnP on router. But if it's disabled by default, he/she may not known to enable it.
